In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("/content/NC par régions.xlsx",index_col=0)
data.tail(2)

Région Grand Casablanca-Settat   ...  Région Guelmim Oued Noun 
2021-08-29                             1001  ...                        141
2021-08-30                              325  ...                          8

[2 rows x 12 columns]

In [3]:
Regions=data.columns.values

In [4]:
def split_data(array,input_step,horizon):
    X,Y=[],[]
    for i in range(len(array)):
        idx_last_y=i+input_step+horizon
        if idx_last_y <= len(array):
            Y.append(array[idx_last_y-horizon:idx_last_y])
            X.append(array[i:i+input_step])
        else :
            break
    return np.array(X),np.array(Y)

In [5]:
from tensorflow import keras
from tensorflow.keras import layers

In [6]:
def Makeprediction(NomRegion,var):
    #Prepare data
    NewCase=data[NomRegion].values
    lag=10
    horizon=5
    X,Y=split_data(NewCase,lag,horizon)
    X = X.reshape((X.shape[0], X.shape[1], 1))
    model = keras.Sequential([
    layers.LSTM(200, activation='relu',return_sequences=True, input_shape=(10, 1)),
    layers.LSTM(200,activation='relu'),
    layers.Dense(5),
  ])
    model.compile(optimizer='adam', loss='mae')
    model.fit(X,Y,epochs=100,verbose=0)
    var=np.array(var)
    var=var.astype(float)
    var=var.reshape(1,10,1)
    Y_hat=model.predict(var)
    return Y_hat

In [8]:
valeurs=data.tail(10)
projections=[]
for i in range(len(Regions)):
    nom=Regions[i]
    predictors=list(valeurs[nom].values)
    pre=Makeprediction(nom,predictors)
    projections.append(pre)
    print('Fin :' + nom)
    print('-'*40)

Fin :Région Grand Casablanca-Settat 
----------------------------------------
Fin :Région Marrakech- Safi 
----------------------------------------
Fin :Région Darâa-Tafilalet 
----------------------------------------
Fin :Région Fès - Meknès 
----------------------------------------
Fin :Région Rabat - Salé-Kenitra 
----------------------------------------
Fin :Région Tanger -Tétouan- Al Hoceima 
----------------------------------------
Fin :Région Dakhla-Oued Eddahab 
----------------------------------------
Fin :Région Souss - Massa 
----------------------------------------
Fin :Région Beni Mellal- Khénifra 
----------------------------------------
Fin :Région Oriental 
----------------------------------------
Fin :Région Laâyoune - Sakia El Hamra 
----------------------------------------
Fin :Région Guelmim Oued Noun 
----------------------------------------


In [10]:
projections

[array([[2167.4233, 2286.3064, 2283.7156, 2191.0828, 1754.8181]],
       dtype=float32),
 array([[253.52737, 315.00208, 366.89868, 301.2787 , 287.83084]],
       dtype=float32),
 array([[195.32167, 186.27599, 167.56522, 137.30515, 114.63259]],
       dtype=float32),
 array([[268.074  , 289.49625, 309.32062, 309.68   , 289.94208]],
       dtype=float32),
 array([[1212.271  , 1100.9918 ,  954.10205,  949.5138 , 1027.502  ]],
       dtype=float32),
 array([[635.6597 , 615.2855 , 677.8044 , 705.29724, 676.28046]],
       dtype=float32),
 array([[54.673275, 62.148994, 59.999897, 55.466797, 49.43401 ]],
       dtype=float32),
 array([[251.40535, 274.8115 , 255.51605, 284.39508, 248.62811]],
       dtype=float32),
 array([[256.70975, 263.77774, 347.45108, 284.4407 , 238.54488]],
       dtype=float32),
 array([[599.00183, 529.3906 , 465.8174 , 453.476  , 480.23535]],
       dtype=float32),
 array([[167.10948, 208.3705 , 176.08871, 121.36041, 116.35237]],
       dtype=float32),
 array([[131.886

In [ ]:
Regions

array(['Région Grand Casablanca-Settat ', 'Région Marrakech- Safi ',
       'Région Darâa-Tafilalet ', 'Région Fès - Meknès ',
       'Région Rabat - Salé-Kenitra ',
       'Région Tanger -Tétouan- Al Hoceima ',
       'Région Dakhla-Oued Eddahab ', 'Région Souss - Massa ',
       'Région Beni Mellal- Khénifra ', 'Région Oriental ',
       'Région Laâyoune - Sakia El Hamra ', 'Région Guelmim Oued Noun '],
      dtype=object)