In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("/content/ND par régions.xlsx",index_col=0)
data.tail(2)

Région Grand Casablanca-Settat   ...  Région Guelmim Oued Noun 
2021-08-29                               12  ...                          2
2021-08-30                               20  ...                          3

[2 rows x 12 columns]

In [3]:
Regions=data.columns.values

In [4]:
def split_data(array,input_step,horizon):
    X,Y=[],[]
    for i in range(len(array)):
        idx_last_y=i+input_step+horizon
        if idx_last_y <= len(array):
            Y.append(array[idx_last_y-horizon:idx_last_y])
            X.append(array[i:i+input_step])
        else :
            break
    return np.array(X),np.array(Y)

In [5]:
from tensorflow import keras
from tensorflow.keras import layers

In [6]:
def Makeprediction(NomRegion,var):
    #Prepare data
    NewCase=data[NomRegion].values
    lag=10
    horizon=5
    X,Y=split_data(NewCase,lag,horizon)
    X = X.reshape((X.shape[0], X.shape[1], 1))
    model = keras.Sequential([
    layers.LSTM(30, activation='relu',return_sequences=True, input_shape=(10, 1)),
    layers.LSTM(30,activation='relu'),
    layers.Dense(5),
  ])
    model.compile(optimizer='adam', loss='mae')
    model.fit(X,Y,epochs=70,verbose=0)
    var=np.array(var)
    var=var.astype(float)
    var=var.reshape(1,10,1)
    Y_hat=model.predict(var)
    return Y_hat

In [7]:
valeurs=data.tail(10)
projections=[]
for i in range(len(Regions)):
    nom=Regions[i]
    predictors=list(valeurs[nom].values)
    pre=Makeprediction(nom,predictors)
    projections.append(pre)
    print('Fin :' + nom)
    print('-'*40)

Fin :Région Grand Casablanca-Settat 
----------------------------------------
Fin :Région Marrakech- Safi 
----------------------------------------
Fin :Région Darâa-Tafilalet 
----------------------------------------
Fin :Région Fès - Meknès 
----------------------------------------
Fin :Région Rabat - Salé-Kenitra 
----------------------------------------
Fin :Région Tanger -Tétouan- Al Hoceima 
----------------------------------------
Fin :Région Dakhla-Oued Eddahab 
----------------------------------------
Fin :Région Souss - Massa 
----------------------------------------
Fin :Région Beni Mellal- Khénifra 
----------------------------------------
Fin :Région Oriental 
----------------------------------------
Fin :Région Laâyoune - Sakia El Hamra 
----------------------------------------
Fin :Région Guelmim Oued Noun 
----------------------------------------


In [8]:
projections

[array([[16.686327, 16.128693, 16.817413, 18.496002, 16.836004]],
       dtype=float32),
 array([[10.733106, 10.920736, 10.354726, 10.698125, 10.014041]],
       dtype=float32),
 array([[3.4607208, 3.0951498, 3.5053566, 2.3369977, 2.81813  ]],
       dtype=float32),
 array([[4.6768465, 4.404902 , 5.001992 , 5.2701387, 5.3478312]],
       dtype=float32),
 array([[13.611649,  8.695037,  8.791894, 12.901319, 13.527157]],
       dtype=float32),
 array([[11.926116 ,  8.365306 ,  8.874212 ,  9.791156 ,  7.4735837]],
       dtype=float32),
 array([[-7.5197764e-05,  5.8303307e-05,  1.4647769e-04,  4.2136344e-05,
          6.0305960e-05]], dtype=float32),
 array([[11.56175 ,  9.235855,  9.83405 ,  8.358902,  8.048911]],
       dtype=float32),
 array([[8.810342 , 6.946575 , 6.0875735, 6.591528 , 5.9141445]],
       dtype=float32),
 array([[7.32225  , 7.540166 , 9.684834 , 9.284021 , 5.9539433]],
       dtype=float32),
 array([[2.5730922, 2.7023778, 2.539502 , 2.0661516, 2.0713282]],
       dtype